# Generated by Django 3.1.4 on 2020-12-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pizzaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfPizza', models.CharField(max_length=1000)),
                ('sizeOfPizza', models.CharField(max_length=1000)),
                ('toppingOfPizza', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='pizzaSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizeOfPizza', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='pizzaTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppingOfPizza', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='typeOfPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfPizza', models.CharField(max_length=1000)),
            ],
        ),
    ]
